2024-12-04 21:51:40,179 ERROR: Exception on / [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/main/routes.py", line 12, in index
    return render_template('index.html')
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 223, in top-level template code
    <strong>&copy; {{ now.year }} Portal</strong>
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'now' is undefined
2024-12-04 21:51:40,977 ERROR: Exception on / [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/main/routes.py", line 12, in index
    return render_template('index.html')
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 223, in top-level template code
    <strong>&copy; {{ now.year }} Portal</strong>
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'now' is undefined
2024-12-04 21:53:11,708 INFO: Application startup [in /Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/__init__.py:71]
2024-12-04 21:53:11,947 INFO: Application startup [in /Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/__init__.py:71]
2024-12-04 21:53:12,178 INFO: Application startup [in /Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/__init__.py:71]
2024-12-04 21:53:22,609 ERROR: Exception on /profile [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/main/routes.py", line 70, in profile
    return render_template('profile.html', activities=activities)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/profile.html", line 63, in template
    <td>{{ activity.timestamp|datetime }}</td>
jinja2.exceptions.TemplateAssertionError: No filter named 'datetime'.
2024-12-04 21:56:37,710 INFO: Application startup [in /Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/__init__.py:71]
