2024-12-04 21:47:43,329 ERROR: Exception on / [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/main/routes.py", line 11, in index
    return render_template('index.html')
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 148, in top-level template code
    {% set nav = navigation_manager.get_user_navigation() %}
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'navigation_manager' is undefined
2024-12-04 21:47:50,627 ERROR: Exception on /login [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/main/routes.py", line 41, in login
    return render_template('login.html')
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 192, in top-level template code
    {% block breadcrumb %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 193, in block 'breadcrumb'
    {% set breadcrumb = navigation_manager.get_breadcrumb(request.path) %}
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'navigation_manager' is undefined
2024-12-04 21:47:55,382 ERROR: Exception on /login [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/main/routes.py", line 41, in login
    return render_template('login.html')
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 192, in top-level template code
    {% block breadcrumb %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 193, in block 'breadcrumb'
    {% set breadcrumb = navigation_manager.get_breadcrumb(request.path) %}
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'navigation_manager' is undefined
2024-12-04 21:47:57,832 ERROR: Exception on /login [GET] [in /Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/main/routes.py", line 41, in login
    return render_template('login.html')
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 192, in top-level template code
    {% block breadcrumb %}
  File "/Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/templates/base.html", line 193, in block 'breadcrumb'
    {% set breadcrumb = navigation_manager.get_breadcrumb(request.path) %}
  File "/Users/justin/Projects/flask_portal/venv/lib/python3.10/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'navigation_manager' is undefined
2024-12-04 21:48:38,729 INFO: Application startup [in /Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/__init__.py:62]
2024-12-04 21:48:38,966 INFO: Application startup [in /Users/justin/Downloads/4th_quarter_2024_flask-blackfridaylunch/app/__init__.py:62]
